WIP - Experimental compressed memory cache
Imprex-Development/orebfuscator pull request #386
Opened 2024-08-08 19:14 UTC by Ingrim4

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-08-29 17:33 UTC, Ingrim4 commented on orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/OrebfuscatorStatistics.java
> +		double memoryCacheHitRate = (double) cacheHitCountMemory / totalCacheRequest;
division by zero

2024-09-11 16:21 UTC, NgLoader requested changes
Code lgtm, config files need to be updated

2024-10-07 21:23 UTC, NgLoader submitted a review, later dismissed
LGTM

2024-10-07 22:19 UTC, NgLoader approved these changes, later dismissed

2024-10-07 22:52 UTC, NgLoader submitted a review, later dismissed

2024-10-07 23:04 UTC, NgLoader approved these changes

2024-10-07 23:06 UTC, merged